dist: bionic

language: php

sudo: false

addons:
  firefox: "47.0.1"
  postgresql: "9.6"
  apt:
    packages:
      - default-jre

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
 - 7.1
 - 7.2
 - 7.4

env:
  - DB=pgsql  MOODLE_BRANCH=MOODLE_38_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
  - DB=pgsql  MOODLE_BRANCH=MOODLE_39_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE

jobs:
  exclude:
    # Moodle 3.9 requires PHP 7.2 and up so exclude PHP 7.1 jobs for 3.9.
    - php: 7.1
      env: DB=pgsql   MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.1
      env: DB=mysqli  MOODLE_BRANCH=MOODLE_39_STABLE

    # Moodle 3.8's minimum supported PHP version is 7.1. So no need to run jobs for PHP 7.2.
    - php: 7.2
      env: DB=pgsql   MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.2
      env: DB=mysqli  MOODLE_BRANCH=MOODLE_38_STABLE

before_install:
  - phpenv config-rm xdebug.ini
  - nvm install 14
  - nvm use 14
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  # Disabling the mustache task as this is currently incompatible with the bionic distro.
  #- moodle-plugin-ci mustache
  - moodle-plugin-ci grunt -t eslint:amd -t babel
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
